export function finalFreshCloneAuditPrompt() {
  return [
    'Run tools now.',
    '',
    'Perform a Final Fresh Clone Readiness Audit for Meridian PR #7 controlled hybrid auto-close smoke readiness.',
    '',
    'Scope:',
    '- Focus only on PR #7 readiness for the Davis-only controlled hybrid auto-close smoke.',
    '- Do not re-audit all of Meridian.',
    '- Do not treat Codex claims, this working tree, stale local state, or Supabase migration history alone as source of truth.',
    '- Use GitHub source of truth from a fresh clone or fresh PR checkout.',
    '- Cite exact file paths and line numbers for every code claim.',
    '- Quote the relevant code lines for every required safety claim.',
    '',
    'Hard prohibitions:',
    '- Do not touch Supabase.',
    '- Do not apply migrations.',
    '- Do not flip flags.',
    '- Do not deploy anything.',
    '- Do not make code changes.',
    '',
    'Layer 1 - PR / code state:',
    '- Start from a fresh clone or fresh PR checkout.',
    '- Confirm PR #7 HEAD and base.',
    '- Confirm changed files.',
    '- Confirm only public/ct-widget.js changed.',
    '- Confirm PASSIVE_CLOSE_LIVE=false.',
    '- Confirm HYBRID_AUTO_CLOSE_LIVE=true.',
    '- Confirm the hybridAccessConfirmed gate remains intact.',
    '',
    'Layer 2 - Passive-close safety path:',
    '- Quote the close gate.',
    '- Quote the tracked-case invariant.',
    '- Quote resolved/reclassified-only promotion.',
    '- Quote low-confidence shadow-only behavior.',
    '- Quote no-tracked-case close-nothing behavior.',
    '',
    'Layer 3 - Complete-during-reclassification fix:',
    '- Confirm reclass_in_progress_at_complete blocker exists on main / PR branch.',
    '- Run or inspect the passive harness branch if needed.',
    '- Confirm the synthetic harness is green for signature_reclass_at_complete.',
    '- Explicitly state whether the manual corpus is active or inactive.',
    '',
    'Layer 4 - Operational readiness:',
    '- State remaining non-code gates:',
    '  - actual schema/RPC present,',
    '  - holdout or reconciliation posture,',
    '  - cohort scope,',
    '  - smoke checklist ready.',
    '',
    'Return format:',
    '- Keep it focused and concise.',
    '- Include cited evidence by file path and line number.',
    '- End with exactly one binary smoke verdict:',
    '  READY FOR DAVIS-ONLY SMOKE',
    '  HOLD - BLOCKER FOUND',
  ].join('\n');
}

export function smokeExportReviewPrompt() {
  return [
    'Review this Meridian Port smoke export.',
    '',
    'Focus only on PR #7 controlled hybrid auto-close smoke readiness.',
    'Identify failed, blocked, weakly evidenced, or missing smoke items.',
    'Do not broaden into passive-close readiness.',
    '',
    'Return:',
    '- Key blockers',
    '- Evidence gaps',
    '- Whether the final decision matches the recorded smoke results',
    '- One recommendation: proceed, hold, or rollback',
  ].join('\n');
}

export function rollbackReviewPrompt() {
  return [
    'Review whether Meridian PR #7 scoped hybrid auto-close should be rolled back.',
    '',
    'Use only the supplied smoke evidence and final decision.',
    'Do not touch Supabase, deploys, migrations, or feature flags.',
    '',
    'Return:',
    '- Rollback trigger, if any',
    '- Evidence supporting rollback or continued hold',
    '- Exact human next step',
  ].join('\n');
}

export const MERIDIAN_PROMPTS = [
  {
    id: 'fresh-clone-audit',
    title: 'Final Fresh Clone Audit Prompt',
    description: 'Forces source-of-truth PR #7 readiness evidence before live smoke.',
    getText: finalFreshCloneAuditPrompt,
  },
  {
    id: 'smoke-export-review',
    title: 'Smoke Export Review Prompt',
    description: 'Reviews exported smoke evidence for blockers and weak spots.',
    getText: smokeExportReviewPrompt,
  },
  {
    id: 'rollback-review',
    title: 'Rollback Review Prompt',
    description: 'Checks whether smoke evidence supports rollback, hold, or continuing.',
    getText: rollbackReviewPrompt,
  },
];
